// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancepackage"
)

// BalancePackageCreate is the builder for creating a BalancePackage entity.
type BalancePackageCreate struct {
	config
	mutation *BalancePackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *BalancePackageCreate) SetName(v string) *BalancePackageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BalancePackageCreate) SetDescription(v string) *BalancePackageCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableDescription(v *string) *BalancePackageCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *BalancePackageCreate) SetPrice(v float64) *BalancePackageCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetCreditAmount sets the "credit_amount" field.
func (_c *BalancePackageCreate) SetCreditAmount(v float64) *BalancePackageCreate {
	_c.mutation.SetCreditAmount(v)
	return _c
}

// SetPackageScope sets the "package_scope" field.
func (_c *BalancePackageCreate) SetPackageScope(v string) *BalancePackageCreate {
	_c.mutation.SetPackageScope(v)
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *BalancePackageCreate) SetProductName(v string) *BalancePackageCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableProductName(v *string) *BalancePackageCreate {
	if v != nil {
		_c.SetProductName(*v)
	}
	return _c
}

// SetDisplayTags sets the "display_tags" field.
func (_c *BalancePackageCreate) SetDisplayTags(v []string) *BalancePackageCreate {
	_c.mutation.SetDisplayTags(v)
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *BalancePackageCreate) SetForSale(v bool) *BalancePackageCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableForSale(v *bool) *BalancePackageCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *BalancePackageCreate) SetSortOrder(v int) *BalancePackageCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableSortOrder(v *int) *BalancePackageCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalancePackageCreate) SetCreatedAt(v time.Time) *BalancePackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableCreatedAt(v *time.Time) *BalancePackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BalancePackageCreate) SetUpdatedAt(v time.Time) *BalancePackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableUpdatedAt(v *time.Time) *BalancePackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BalancePackageMutation object of the builder.
func (_c *BalancePackageCreate) Mutation() *BalancePackageMutation {
	return _c.mutation
}

// Save creates the BalancePackage in the database.
func (_c *BalancePackageCreate) Save(ctx context.Context) (*BalancePackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalancePackageCreate) SaveX(ctx context.Context) *BalancePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalancePackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalancePackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalancePackageCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := balancepackage.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		v := balancepackage.DefaultProductName
		_c.mutation.SetProductName(v)
	}
	if _, ok := _c.mutation.DisplayTags(); !ok {
		v := balancepackage.DefaultDisplayTags
		_c.mutation.SetDisplayTags(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := balancepackage.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := balancepackage.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balancepackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := balancepackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalancePackageCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BalancePackage.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := balancepackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "BalancePackage.description"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "BalancePackage.price"`)}
	}
	if _, ok := _c.mutation.CreditAmount(); !ok {
		return &ValidationError{Name: "credit_amount", err: errors.New(`ent: missing required field "BalancePackage.credit_amount"`)}
	}
	if _, ok := _c.mutation.PackageScope(); !ok {
		return &ValidationError{Name: "package_scope", err: errors.New(`ent: missing required field "BalancePackage.package_scope"`)}
	}
	if v, ok := _c.mutation.PackageScope(); ok {
		if err := balancepackage.PackageScopeValidator(v); err != nil {
			return &ValidationError{Name: "package_scope", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.package_scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "BalancePackage.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := balancepackage.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayTags(); !ok {
		return &ValidationError{Name: "display_tags", err: errors.New(`ent: missing required field "BalancePackage.display_tags"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "BalancePackage.for_sale"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "BalancePackage.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalancePackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BalancePackage.updated_at"`)}
	}
	return nil
}

func (_c *BalancePackageCreate) sqlSave(ctx context.Context) (*BalancePackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalancePackageCreate) createSpec() (*BalancePackage, *sqlgraph.CreateSpec) {
	var (
		_node = &BalancePackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancepackage.Table, sqlgraph.NewFieldSpec(balancepackage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(balancepackage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(balancepackage.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(balancepackage.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.CreditAmount(); ok {
		_spec.SetField(balancepackage.FieldCreditAmount, field.TypeFloat64, value)
		_node.CreditAmount = value
	}
	if value, ok := _c.mutation.PackageScope(); ok {
		_spec.SetField(balancepackage.FieldPackageScope, field.TypeString, value)
		_node.PackageScope = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(balancepackage.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.DisplayTags(); ok {
		_spec.SetField(balancepackage.FieldDisplayTags, field.TypeJSON, value)
		_node.DisplayTags = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(balancepackage.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(balancepackage.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balancepackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(balancepackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalancePackage.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalancePackageUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *BalancePackageCreate) OnConflict(opts ...sql.ConflictOption) *BalancePackageUpsertOne {
	_c.conflict = opts
	return &BalancePackageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalancePackageCreate) OnConflictColumns(columns ...string) *BalancePackageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalancePackageUpsertOne{
		create: _c,
	}
}

type (
	// BalancePackageUpsertOne is the builder for "upsert"-ing
	//  one BalancePackage node.
	BalancePackageUpsertOne struct {
		create *BalancePackageCreate
	}

	// BalancePackageUpsert is the "OnConflict" setter.
	BalancePackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *BalancePackageUpsert) SetName(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateName() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *BalancePackageUpsert) SetDescription(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateDescription() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldDescription)
	return u
}

// SetPrice sets the "price" field.
func (u *BalancePackageUpsert) SetPrice(v float64) *BalancePackageUpsert {
	u.Set(balancepackage.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdatePrice() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *BalancePackageUpsert) AddPrice(v float64) *BalancePackageUpsert {
	u.Add(balancepackage.FieldPrice, v)
	return u
}

// SetCreditAmount sets the "credit_amount" field.
func (u *BalancePackageUpsert) SetCreditAmount(v float64) *BalancePackageUpsert {
	u.Set(balancepackage.FieldCreditAmount, v)
	return u
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateCreditAmount() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldCreditAmount)
	return u
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *BalancePackageUpsert) AddCreditAmount(v float64) *BalancePackageUpsert {
	u.Add(balancepackage.FieldCreditAmount, v)
	return u
}

// SetPackageScope sets the "package_scope" field.
func (u *BalancePackageUpsert) SetPackageScope(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldPackageScope, v)
	return u
}

// UpdatePackageScope sets the "package_scope" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdatePackageScope() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldPackageScope)
	return u
}

// SetProductName sets the "product_name" field.
func (u *BalancePackageUpsert) SetProductName(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateProductName() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldProductName)
	return u
}

// SetDisplayTags sets the "display_tags" field.
func (u *BalancePackageUpsert) SetDisplayTags(v []string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldDisplayTags, v)
	return u
}

// UpdateDisplayTags sets the "display_tags" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateDisplayTags() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldDisplayTags)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *BalancePackageUpsert) SetForSale(v bool) *BalancePackageUpsert {
	u.Set(balancepackage.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateForSale() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldForSale)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *BalancePackageUpsert) SetSortOrder(v int) *BalancePackageUpsert {
	u.Set(balancepackage.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateSortOrder() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalancePackageUpsert) AddSortOrder(v int) *BalancePackageUpsert {
	u.Add(balancepackage.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalancePackageUpsert) SetUpdatedAt(v time.Time) *BalancePackageUpsert {
	u.Set(balancepackage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateUpdatedAt() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalancePackageUpsertOne) UpdateNewValues() *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balancepackage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalancePackageUpsertOne) Ignore() *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalancePackageUpsertOne) DoNothing() *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalancePackageCreate.OnConflict
// documentation for more info.
func (u *BalancePackageUpsertOne) Update(set func(*BalancePackageUpsert)) *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalancePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BalancePackageUpsertOne) SetName(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateName() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *BalancePackageUpsertOne) SetDescription(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateDescription() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateDescription()
	})
}

// SetPrice sets the "price" field.
func (u *BalancePackageUpsertOne) SetPrice(v float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *BalancePackageUpsertOne) AddPrice(v float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdatePrice() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdatePrice()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *BalancePackageUpsertOne) SetCreditAmount(v float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *BalancePackageUpsertOne) AddCreditAmount(v float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateCreditAmount() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCreditAmount()
	})
}

// SetPackageScope sets the "package_scope" field.
func (u *BalancePackageUpsertOne) SetPackageScope(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetPackageScope(v)
	})
}

// UpdatePackageScope sets the "package_scope" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdatePackageScope() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdatePackageScope()
	})
}

// SetProductName sets the "product_name" field.
func (u *BalancePackageUpsertOne) SetProductName(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateProductName() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateProductName()
	})
}

// SetDisplayTags sets the "display_tags" field.
func (u *BalancePackageUpsertOne) SetDisplayTags(v []string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetDisplayTags(v)
	})
}

// UpdateDisplayTags sets the "display_tags" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateDisplayTags() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateDisplayTags()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BalancePackageUpsertOne) SetForSale(v bool) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateForSale() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BalancePackageUpsertOne) SetSortOrder(v int) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalancePackageUpsertOne) AddSortOrder(v int) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateSortOrder() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalancePackageUpsertOne) SetUpdatedAt(v time.Time) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateUpdatedAt() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalancePackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalancePackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalancePackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalancePackageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalancePackageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalancePackageCreateBulk is the builder for creating many BalancePackage entities in bulk.
type BalancePackageCreateBulk struct {
	config
	err      error
	builders []*BalancePackageCreate
	conflict []sql.ConflictOption
}

// Save creates the BalancePackage entities in the database.
func (_c *BalancePackageCreateBulk) Save(ctx context.Context) ([]*BalancePackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalancePackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalancePackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalancePackageCreateBulk) SaveX(ctx context.Context) []*BalancePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalancePackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalancePackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalancePackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalancePackageUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *BalancePackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalancePackageUpsertBulk {
	_c.conflict = opts
	return &BalancePackageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalancePackageCreateBulk) OnConflictColumns(columns ...string) *BalancePackageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalancePackageUpsertBulk{
		create: _c,
	}
}

// BalancePackageUpsertBulk is the builder for "upsert"-ing
// a bulk of BalancePackage nodes.
type BalancePackageUpsertBulk struct {
	create *BalancePackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalancePackageUpsertBulk) UpdateNewValues() *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balancepackage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalancePackageUpsertBulk) Ignore() *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalancePackageUpsertBulk) DoNothing() *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalancePackageCreateBulk.OnConflict
// documentation for more info.
func (u *BalancePackageUpsertBulk) Update(set func(*BalancePackageUpsert)) *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalancePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BalancePackageUpsertBulk) SetName(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateName() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *BalancePackageUpsertBulk) SetDescription(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateDescription() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateDescription()
	})
}

// SetPrice sets the "price" field.
func (u *BalancePackageUpsertBulk) SetPrice(v float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *BalancePackageUpsertBulk) AddPrice(v float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdatePrice() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdatePrice()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *BalancePackageUpsertBulk) SetCreditAmount(v float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *BalancePackageUpsertBulk) AddCreditAmount(v float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateCreditAmount() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCreditAmount()
	})
}

// SetPackageScope sets the "package_scope" field.
func (u *BalancePackageUpsertBulk) SetPackageScope(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetPackageScope(v)
	})
}

// UpdatePackageScope sets the "package_scope" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdatePackageScope() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdatePackageScope()
	})
}

// SetProductName sets the "product_name" field.
func (u *BalancePackageUpsertBulk) SetProductName(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateProductName() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateProductName()
	})
}

// SetDisplayTags sets the "display_tags" field.
func (u *BalancePackageUpsertBulk) SetDisplayTags(v []string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetDisplayTags(v)
	})
}

// UpdateDisplayTags sets the "display_tags" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateDisplayTags() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateDisplayTags()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BalancePackageUpsertBulk) SetForSale(v bool) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateForSale() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BalancePackageUpsertBulk) SetSortOrder(v int) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalancePackageUpsertBulk) AddSortOrder(v int) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateSortOrder() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalancePackageUpsertBulk) SetUpdatedAt(v time.Time) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateUpdatedAt() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalancePackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalancePackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalancePackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalancePackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
