// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancepackage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalancePackageUpdate is the builder for updating BalancePackage entities.
type BalancePackageUpdate struct {
	config
	hooks    []Hook
	mutation *BalancePackageMutation
}

// Where appends a list predicates to the BalancePackageUpdate builder.
func (_u *BalancePackageUpdate) Where(ps ...predicate.BalancePackage) *BalancePackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BalancePackageUpdate) SetName(v string) *BalancePackageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillableName(v *string) *BalancePackageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalancePackageUpdate) SetDescription(v string) *BalancePackageUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillableDescription(v *string) *BalancePackageUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BalancePackageUpdate) SetPrice(v float64) *BalancePackageUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillablePrice(v *float64) *BalancePackageUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BalancePackageUpdate) AddPrice(v float64) *BalancePackageUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *BalancePackageUpdate) SetCreditAmount(v float64) *BalancePackageUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillableCreditAmount(v *float64) *BalancePackageUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *BalancePackageUpdate) AddCreditAmount(v float64) *BalancePackageUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetPackageScope sets the "package_scope" field.
func (_u *BalancePackageUpdate) SetPackageScope(v string) *BalancePackageUpdate {
	_u.mutation.SetPackageScope(v)
	return _u
}

// SetNillablePackageScope sets the "package_scope" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillablePackageScope(v *string) *BalancePackageUpdate {
	if v != nil {
		_u.SetPackageScope(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *BalancePackageUpdate) SetProductName(v string) *BalancePackageUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillableProductName(v *string) *BalancePackageUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetDisplayTags sets the "display_tags" field.
func (_u *BalancePackageUpdate) SetDisplayTags(v []string) *BalancePackageUpdate {
	_u.mutation.SetDisplayTags(v)
	return _u
}

// AppendDisplayTags appends value to the "display_tags" field.
func (_u *BalancePackageUpdate) AppendDisplayTags(v []string) *BalancePackageUpdate {
	_u.mutation.AppendDisplayTags(v)
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *BalancePackageUpdate) SetForSale(v bool) *BalancePackageUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillableForSale(v *bool) *BalancePackageUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BalancePackageUpdate) SetSortOrder(v int) *BalancePackageUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BalancePackageUpdate) SetNillableSortOrder(v *int) *BalancePackageUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BalancePackageUpdate) AddSortOrder(v int) *BalancePackageUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalancePackageUpdate) SetUpdatedAt(v time.Time) *BalancePackageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BalancePackageMutation object of the builder.
func (_u *BalancePackageUpdate) Mutation() *BalancePackageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalancePackageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalancePackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalancePackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalancePackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalancePackageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancepackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalancePackageUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := balancepackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackageScope(); ok {
		if err := balancepackage.PackageScopeValidator(v); err != nil {
			return &ValidationError{Name: "package_scope", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.package_scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := balancepackage.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.product_name": %w`, err)}
		}
	}
	return nil
}

func (_u *BalancePackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancepackage.Table, balancepackage.Columns, sqlgraph.NewFieldSpec(balancepackage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(balancepackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balancepackage.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(balancepackage.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(balancepackage.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(balancepackage.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(balancepackage.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PackageScope(); ok {
		_spec.SetField(balancepackage.FieldPackageScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(balancepackage.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayTags(); ok {
		_spec.SetField(balancepackage.FieldDisplayTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDisplayTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, balancepackage.FieldDisplayTags, value)
		})
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(balancepackage.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(balancepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(balancepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancepackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalancePackageUpdateOne is the builder for updating a single BalancePackage entity.
type BalancePackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalancePackageMutation
}

// SetName sets the "name" field.
func (_u *BalancePackageUpdateOne) SetName(v string) *BalancePackageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillableName(v *string) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalancePackageUpdateOne) SetDescription(v string) *BalancePackageUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillableDescription(v *string) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BalancePackageUpdateOne) SetPrice(v float64) *BalancePackageUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillablePrice(v *float64) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BalancePackageUpdateOne) AddPrice(v float64) *BalancePackageUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *BalancePackageUpdateOne) SetCreditAmount(v float64) *BalancePackageUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillableCreditAmount(v *float64) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *BalancePackageUpdateOne) AddCreditAmount(v float64) *BalancePackageUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetPackageScope sets the "package_scope" field.
func (_u *BalancePackageUpdateOne) SetPackageScope(v string) *BalancePackageUpdateOne {
	_u.mutation.SetPackageScope(v)
	return _u
}

// SetNillablePackageScope sets the "package_scope" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillablePackageScope(v *string) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetPackageScope(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *BalancePackageUpdateOne) SetProductName(v string) *BalancePackageUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillableProductName(v *string) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetDisplayTags sets the "display_tags" field.
func (_u *BalancePackageUpdateOne) SetDisplayTags(v []string) *BalancePackageUpdateOne {
	_u.mutation.SetDisplayTags(v)
	return _u
}

// AppendDisplayTags appends value to the "display_tags" field.
func (_u *BalancePackageUpdateOne) AppendDisplayTags(v []string) *BalancePackageUpdateOne {
	_u.mutation.AppendDisplayTags(v)
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *BalancePackageUpdateOne) SetForSale(v bool) *BalancePackageUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillableForSale(v *bool) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BalancePackageUpdateOne) SetSortOrder(v int) *BalancePackageUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BalancePackageUpdateOne) SetNillableSortOrder(v *int) *BalancePackageUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BalancePackageUpdateOne) AddSortOrder(v int) *BalancePackageUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalancePackageUpdateOne) SetUpdatedAt(v time.Time) *BalancePackageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BalancePackageMutation object of the builder.
func (_u *BalancePackageUpdateOne) Mutation() *BalancePackageMutation {
	return _u.mutation
}

// Where appends a list predicates to the BalancePackageUpdate builder.
func (_u *BalancePackageUpdateOne) Where(ps ...predicate.BalancePackage) *BalancePackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalancePackageUpdateOne) Select(field string, fields ...string) *BalancePackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalancePackage entity.
func (_u *BalancePackageUpdateOne) Save(ctx context.Context) (*BalancePackage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalancePackageUpdateOne) SaveX(ctx context.Context) *BalancePackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalancePackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalancePackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalancePackageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancepackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalancePackageUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := balancepackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackageScope(); ok {
		if err := balancepackage.PackageScopeValidator(v); err != nil {
			return &ValidationError{Name: "package_scope", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.package_scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := balancepackage.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.product_name": %w`, err)}
		}
	}
	return nil
}

func (_u *BalancePackageUpdateOne) sqlSave(ctx context.Context) (_node *BalancePackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancepackage.Table, balancepackage.Columns, sqlgraph.NewFieldSpec(balancepackage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalancePackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancepackage.FieldID)
		for _, f := range fields {
			if !balancepackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancepackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(balancepackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balancepackage.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(balancepackage.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(balancepackage.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(balancepackage.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(balancepackage.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PackageScope(); ok {
		_spec.SetField(balancepackage.FieldPackageScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(balancepackage.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayTags(); ok {
		_spec.SetField(balancepackage.FieldDisplayTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDisplayTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, balancepackage.FieldDisplayTags, value)
		})
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(balancepackage.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(balancepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(balancepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancepackage.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BalancePackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
