// Code generated by ent, DO NOT EDIT.

package balancepackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldPrice, v))
}

// CreditAmount applies equality check predicate on the "credit_amount" field. It's identical to CreditAmountEQ.
func CreditAmount(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreditAmount, v))
}

// PackageScope applies equality check predicate on the "package_scope" field. It's identical to PackageScopeEQ.
func PackageScope(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldPackageScope, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldProductName, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldPrice, v))
}

// CreditAmountEQ applies the EQ predicate on the "credit_amount" field.
func CreditAmountEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreditAmount, v))
}

// CreditAmountNEQ applies the NEQ predicate on the "credit_amount" field.
func CreditAmountNEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldCreditAmount, v))
}

// CreditAmountIn applies the In predicate on the "credit_amount" field.
func CreditAmountIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldCreditAmount, vs...))
}

// CreditAmountNotIn applies the NotIn predicate on the "credit_amount" field.
func CreditAmountNotIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldCreditAmount, vs...))
}

// CreditAmountGT applies the GT predicate on the "credit_amount" field.
func CreditAmountGT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldCreditAmount, v))
}

// CreditAmountGTE applies the GTE predicate on the "credit_amount" field.
func CreditAmountGTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldCreditAmount, v))
}

// CreditAmountLT applies the LT predicate on the "credit_amount" field.
func CreditAmountLT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldCreditAmount, v))
}

// CreditAmountLTE applies the LTE predicate on the "credit_amount" field.
func CreditAmountLTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldCreditAmount, v))
}

// PackageScopeEQ applies the EQ predicate on the "package_scope" field.
func PackageScopeEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldPackageScope, v))
}

// PackageScopeNEQ applies the NEQ predicate on the "package_scope" field.
func PackageScopeNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldPackageScope, v))
}

// PackageScopeIn applies the In predicate on the "package_scope" field.
func PackageScopeIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldPackageScope, vs...))
}

// PackageScopeNotIn applies the NotIn predicate on the "package_scope" field.
func PackageScopeNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldPackageScope, vs...))
}

// PackageScopeGT applies the GT predicate on the "package_scope" field.
func PackageScopeGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldPackageScope, v))
}

// PackageScopeGTE applies the GTE predicate on the "package_scope" field.
func PackageScopeGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldPackageScope, v))
}

// PackageScopeLT applies the LT predicate on the "package_scope" field.
func PackageScopeLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldPackageScope, v))
}

// PackageScopeLTE applies the LTE predicate on the "package_scope" field.
func PackageScopeLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldPackageScope, v))
}

// PackageScopeContains applies the Contains predicate on the "package_scope" field.
func PackageScopeContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldPackageScope, v))
}

// PackageScopeHasPrefix applies the HasPrefix predicate on the "package_scope" field.
func PackageScopeHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldPackageScope, v))
}

// PackageScopeHasSuffix applies the HasSuffix predicate on the "package_scope" field.
func PackageScopeHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldPackageScope, v))
}

// PackageScopeEqualFold applies the EqualFold predicate on the "package_scope" field.
func PackageScopeEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldPackageScope, v))
}

// PackageScopeContainsFold applies the ContainsFold predicate on the "package_scope" field.
func PackageScopeContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldPackageScope, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldProductName, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalancePackage) predicate.BalancePackage {
	return predicate.BalancePackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalancePackage) predicate.BalancePackage {
	return predicate.BalancePackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalancePackage) predicate.BalancePackage {
	return predicate.BalancePackage(sql.NotPredicates(p))
}
